{
  "openapi": "3.1.0",
  "info": {
    "title": "Monzo API (Legacy Personal + Open Banking)",
    "version": "1.0.0",
    "description": "Auto-generated OpenAPI 3.1 specification from Monzo's official Markdown documentation",
    "contact": {
      "name": "Generated by monzo-docs"
    }
  },
  "servers": [
    {
      "url": "https://api.monzo.com"
    },
    {
      "url": "https://openbanking.monzo.com/open-banking/v3.1"
    }
  ],
  "tags": [
    {
      "name": "Accounts",
      "description": "Accounts represent a store of funds, and have a list of transactions.\n\n## List accounts"
    },
    {
      "name": "Account Information Services API",
      "description": "The Account Information Services API lets authorised Account Information Service Providers access balances, transactions, \nand more for our customers in the United Kingdom."
    },
    {
      "name": "Attachments",
      "description": "Images (eg. receipts) can be attached to transactions by uploading these via the `attachment` API. Once an attachment is *registered* against a transaction, the image will be shown in the transaction detail screen within the Monzo app.\n\nThere are two options for attaching images to transactions - either Monzo can host the image, or remote images can be displayed."
    },
    {
      "name": "Authentication",
      "description": "The Monzo API implements [OAuth 2.0](http://oauth.net/2/) to allow users to log in to applications without exposing their credentials. The process involves several steps:\n\n1. [**Acquire**](#acquire-an-access-token) an access token, and optionally a refresh token"
    },
    {
      "name": "Balance",
      "description": "Retrieve information about an account's balance.\n\n## Read balance"
    },
    {
      "name": "Confirmation of Funds API",
      "description": "The Confirmation of Funds API lets authorised Card Based Payment Instrument Issuers check that Monzo customers have \nenough money for a purchase."
    },
    {
      "name": "Errors",
      "description": "The Monzo API uses conventional HTTP response codes to indicate errors, and includes more detailed information on the exact nature of an error in the HTTP response.\n\n##### HTTP response codes"
    },
    {
      "name": "EU PSD2 API",
      "description": "<aside class=\"notice\">\n    Monzo's EU PSD2 Dedicated Interface API is currently only available for testing in the sandbox environment. Please get in touch with us at <a href=\"mailto:openbanking@monzo.com\">openbanking@monzo.com</a> if you'd like to test out our APIs. Production API access will be available at a later date.\n</aside>"
    },
    {
      "name": "Feed items",
      "description": "The Monzo app is organised around the feed – a reverse-chronological stream of events. Transactions are one such feed item, and your application can create its own feed items to surface relevant information to the user.\n\nIt's important to keep a few principals in mind when creating feed items:"
    },
    {
      "name": "Open Banking Errors",
      "description": "<aside class=\"notice\">\n    Currently this new error behaviour is only available in our sandbox environment with a production release to be scheduled at a later date. \n</aside>"
    },
    {
      "name": "Expanding objects",
      "description": "Some objects contain the id of another object in their response. To save a round-trip, some of these objects can be expanded inline with the `expand[]` argument, which is repeatable. Objects that can be expanded are noted in individual endpoint documentation."
    },
    {
      "name": "Pagination",
      "description": "Endpoints which enumerate objects support time-based and cursor-based pagination.\n\n##### Request arguments"
    },
    {
      "name": "Payment Initiation Services API",
      "description": "The Payment Initiation Services API lets authorised Payment Initiation Service Providers make outbound payments from \nthe accounts of our customers in the United Kingdom. All payments initiated through our Payment Initiation Services \nAPI are sent through Faster Payments."
    },
    {
      "name": "Pots",
      "description": "A pot is a place to keep some money separate from the main spending account.\n\n## List pots"
    },
    {
      "name": "Receipts",
      "description": "Receipts are line-item purchase data added to a transaction. They contain all the information about the purchase, including the products you bought, any taxes that were added on, and how you paid. They can also contain extra details about the merchant you spent money at, such as how to contact them, but this may not appear in the app yet.\n\nThis is the API currently used by [Flux](https://monzo.com/blog/2019/01/31/flux-monzo-launch/) to show receipts at selected retailers in your Monzo app."
    },
    {
      "name": "SCA-RTS (PS21/19)",
      "description": "## Overview\nIn November 2021, the FCA set out new rules for standards on Strong Customer Authentication (SCA) in a change to the Regulatory Technical Standards on Strong Customer Authentication and Secure Communication (SCA-RTS)."
    },
    {
      "name": "Transactions",
      "description": "Transactions are movements of funds into or out of an account. Negative transactions represent debits (ie. *spending* money) and positive transactions represent credits (ie. *receiving* money).\n\nMost properties on transactions are self-explanatory. We'll eventually get around to documenting them all, but in the meantime let's discuss the most interesting/confusing ones:"
    },
    {
      "name": "Variable Recurring Payments API",
      "description": "The Variable Recurring Payments (VRP) API lets authorised Payment Initiation Service Providers make outbound payments\nfrom the accounts of our customers in the United Kingdom. Variable Recurring Payments enable multiple payments to be\nmade under a single long-lived consent without the need for authenticating and approving each payment. Further"
    },
    {
      "name": "Webhooks",
      "description": "Webhooks allow your application to receive real-time, push notification of events in an account.\n\n## Registering a webhook"
    }
  ],
  "paths": {
    "/attachment/upload": {
      "post": {
        "summary": "Upload attachment",
        "operationId": "post__attachment_upload",
        "tags": [
          "Attachments"
        ],
        "parameters": [

        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "example": {
                  "file_url": "https://s3-eu-west-1.amazonaws.com/mondo-image-uploads/user_00009237hliZellUicKuG1/LcCu4ogv1xW28OCcvOTL-foo.png",
                  "upload_url": "https://mondo-image-uploads.s3.amazonaws.com/user_00009237hliZellUicKuG1/LcCu4ogv1xW28OCcvOTL-foo.png?AWSAccessKeyId={EXAMPLE_AWS_ACCESS_KEY_ID}&Expires=1447353431&Signature=k2QeDCCQQHaZeynzYKckejqXRGU%!D(MISSING)"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "example": {
                "file_url": "https://s3-eu-west-1.amazonaws.com/mondo-image-uploads/user_00009237hliZellUicKuG1/LcCu4ogv1xW28OCcvOTL-foo.png",
                "upload_url": "https://mondo-image-uploads.s3.amazonaws.com/user_00009237hliZellUicKuG1/LcCu4ogv1xW28OCcvOTL-foo.png?AWSAccessKeyId={EXAMPLE_AWS_ACCESS_KEY_ID}&Expires=1447353431&Signature=k2QeDCCQQHaZeynzYKckejqXRGU%!D(MISSING)"
              }
            }
          }
        }
      },
      "post": {
        "summary": "Obtain pre-signed upload URL",
        "tags": [
          "Attachments"
        ],
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ]
      }
    },
    "/attachment/register": {
      "post": {
        "summary": "Upload attachment",
        "operationId": "post__attachment_register",
        "tags": [
          "Attachments"
        ],
        "parameters": [

        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "example": {
                  "attachment": {
                    "id": "attach_00009238aOAIvVqfb9LrZh",
                    "user_id": "user_00009238aMBIIrS5Rdncq9",
                    "external_id": "tx_00008zIcpb1TB4yeIFXMzx",
                    "file_url": "https://s3-eu-west-1.amazonaws.com/mondo-image-uploads/user_00009237hliZellUicKuG1/LcCu4ogv1xW28OCcvOTL-foo.png",
                    "file_type": "image/png",
                    "created": "2015-11-12T18:37:02Z"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "example": {
                "attachment": {
                  "id": "attach_00009238aOAIvVqfb9LrZh",
                  "user_id": "user_00009238aMBIIrS5Rdncq9",
                  "external_id": "tx_00008zIcpb1TB4yeIFXMzx",
                  "file_url": "https://s3-eu-west-1.amazonaws.com/mondo-image-uploads/user_00009237hliZellUicKuG1/LcCu4ogv1xW28OCcvOTL-foo.png",
                  "file_type": "image/png",
                  "created": "2015-11-12T18:37:02Z"
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Register attachment against transaction",
        "tags": [
          "Attachments"
        ],
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ]
      }
    },
    "/attachment/deregister": {
      "post": {
        "summary": "Upload attachment",
        "operationId": "post__attachment_deregister",
        "tags": [
          "Attachments"
        ],
        "parameters": [

        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "example": {
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "example": {
              }
            }
          }
        }
      },
      "post": {
        "summary": "Deregister attachment",
        "tags": [
          "Attachments"
        ],
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ]
      }
    },
    "/oauth2/token": {
      "post": {
        "summary": "Acquire an access token",
        "operationId": "post__oauth2_token",
        "tags": [
          "Authentication"
        ],
        "parameters": [

        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "example": {
                  "access_token": "access_token_2",
                  "client_id": "client_id",
                  "expires_in": 21600,
                  "refresh_token": "refresh_token_2",
                  "token_type": "Bearer",
                  "user_id": "user_id"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "example": {
                "access_token": "access_token_2",
                "client_id": "client_id",
                "expires_in": 21600,
                "refresh_token": "refresh_token_2",
                "token_type": "Bearer",
                "user_id": "user_id"
              }
            }
          }
        }
      }
    },
    "/oauth2/logout": {
      "post": {
        "summary": "Acquire an access token",
        "operationId": "post__oauth2_logout",
        "tags": [
          "Authentication"
        ],
        "parameters": [

        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
            }
          }
        },
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ]
      }
    },
    "/feed": {
      "post": {
        "summary": "Create feed item",
        "operationId": "post__feed",
        "tags": [
          "Feed items"
        ],
        "parameters": [

        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "example": {
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "example": {
              }
            }
          }
        }
      }
    },
    "/pots/{pot_id}/deposit": {
      "put": {
        "summary": "List pots",
        "operationId": "put__pots_pot_id_deposit",
        "tags": [
          "Pots"
        ],
        "parameters": [

        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
            }
          }
        },
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ]
      }
    },
    "/pots/{pot_id}/withdraw": {
      "put": {
        "summary": "List pots",
        "operationId": "put__pots_pot_id_withdraw",
        "tags": [
          "Pots"
        ],
        "parameters": [

        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
            }
          }
        },
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ]
      }
    },
    "/transaction-receipts": {
      "put": {
        "summary": "Receipt Items",
        "operationId": "put__transactionreceipts",
        "tags": [
          "Receipts"
        ],
        "parameters": [

        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "example": {
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "example": {
              }
            }
          }
        }
      }
    },
    "/transactions/{transaction_id}": {
      "patch": {
        "summary": "Retrieve transaction",
        "operationId": "patch__transactions_transaction_id",
        "tags": [
          "Transactions"
        ],
        "parameters": [

        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "example": {
                  "transaction": {
                    "amount": -679,
                    "created": "2015-08-23T16:15:03Z",
                    "currency": "GBP",
                    "description": "VUE BSL LTD            ISLINGTON     GBR",
                    "id": "tx_00008zL2INM3xZ41THuRF3",
                    "merchant": "merch_00008z6uFVhVBcaZzSQwCX",
                    "metadata": {
                      "foo": "bar"
                    },
                    "notes": "",
                    "is_load": false,
                    "settled": "2015-08-24T16:15:03Z",
                    "category": "eating_out"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "example": {
                "transaction": {
                  "amount": -679,
                  "created": "2015-08-23T16:15:03Z",
                  "currency": "GBP",
                  "description": "VUE BSL LTD            ISLINGTON     GBR",
                  "id": "tx_00008zL2INM3xZ41THuRF3",
                  "merchant": "merch_00008z6uFVhVBcaZzSQwCX",
                  "metadata": {
                    "foo": "bar"
                  },
                  "notes": "",
                  "is_load": false,
                  "settled": "2015-08-24T16:15:03Z",
                  "category": "eating_out"
                }
              }
            }
          }
        }
      }
    },
    "/webhooks": {
      "post": {
        "summary": "Registering a webhook",
        "operationId": "post__webhooks",
        "tags": [
          "Webhooks"
        ],
        "parameters": [

        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "example": {
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "example": {
              }
            }
          }
        }
      }
    },
    "/webhooks/{webhook_id}": {
      "delete": {
        "summary": "Registering a webhook",
        "operationId": "delete__webhooks_webhook_id",
        "tags": [
          "Webhooks"
        ],
        "parameters": [

        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "example": {
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "example": {
              }
            }
          }
        }
      }
    },
    "/ping/whoami": {
      "get": {
        "summary": "Verify authentication (whoami)",
        "operationId": "get_ping_whoami",
        "tags": [
          "Authentication"
        ],
        "responses": {
          "200": {
            "description": "Authenticated",
            "content": {
              "application/json": {
                "example": {
                  "authenticated": true,
                  "client_id": "oauthclient_...",
                  "user_id": "user_..."
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "description": "Personal API access token obtained via OAuth 2.0"
      },
      "openBankingAuth": {
        "type": "oauth2",
        "description": "Open Banking OAuth2 flow (tls_client_auth)",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://auth.monzo.com",
            "tokenUrl": "https://api.monzo.com/oauth2/token",
            "scopes": {
            }
          }
        }
      }
    }
  },
  "security": [
    {
      "bearerAuth": [

      ]
    }
  ]
}